version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      USER_SERVICE_URL: http://user-service:8081
      PRODUCT_SERVICE_URL: http://product-service:8082
      ORDER_SERVICE_URL: http://order-service:8083
    depends_on:
      - user-service
      - product-service
      - order-service

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      DB_URL: postgres://user:password@db:5432/user_service
    depends_on:
      - db

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    environment:
      DB_URL: postgres://user:password@db:5432/product_service
    depends_on:
      - db

  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
    environment:
      DB_URL: postgres://user:password@db:5432/order_service
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

  load-balancer:
    build: ./load-balancer
    ports:
      - "80:80"
    depends_on:
      - api-gateway
      - user-service
      - product-service
      - order-service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
